FROM m.daocloud.io/docker.io/nginx:alpine

RUN apk add --no-cache wget unzip

# 将本地下载的工具文件复制到镜像中
COPY tools/cyberedge-front.zip /tmp/frontend.zip

# 解压文件并清理
RUN unzip -o /tmp/frontend.zip -d /usr/share/nginx/html/ && \
    rm /tmp/frontend.zip

# 复制自定义的 Nginx 配置
COPY tools/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 47808